<?php
/**
 * THIS FILE IS OWNED BY THE FRAMEWORK.
 *
 * Any change you make here is OVERWRITTEN on the next framework update
 * (php artisan rsx:framework:pull hard-syncs it, and a local edit is refused
 * by the tamper gate until you drop it). Do not edit this file.
 *
 * To add your own HTTP middleware, declare it in config - never here:
 *
 *     // rsx/resource/config/rsx.php
 *     'middleware' => [
 *         'global'  => [\App\Http\Middleware\My_Middleware::class],
 *         'web'     => [],
 *         'api'     => [],
 *         'aliases' => ['my_alias' => \App\Http\Middleware\My_Middleware::class],
 *     ],
 *
 * The declaration is APPEND-ONLY: your middleware always runs AFTER the
 * framework stack, and nothing in config can reorder or remove a framework
 * middleware. If you genuinely need that, file a framework change request.
 *
 * See: php artisan rsx:man config_rsx
 *
 * CODING CONVENTION:
 * snake_case for variable_names and function_names. The camelCase properties
 * below are Laravel's, inherited from Illuminate\Foundation\Http\Kernel.
 */

namespace App\Http;

use RuntimeException;
use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array<int, class-string|string>
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Illuminate\Http\Middleware\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        // RSX Framework: Empty strings should remain empty strings, not be converted to null
        // This allows developers to distinguish between "no value provided" and "empty value provided"
        // \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        // Custom RSX middleware
        \App\Http\Middleware\CheckMigrationMode::class,
        \App\Http\Middleware\PlaywrightTestMode::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array<string, array<int, class-string|string>>
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            // Session middleware removed for custom session handler
            // \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            // \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Jqhtml\LaravelBridge\Middleware\JqhtmlErrorMiddleware::class,
        ],

        'api' => [
            // \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            \Illuminate\Routing\Middleware\ThrottleRequests::class.':api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];

    /**
     * The application's middleware aliases.
     *
     * Aliases may be used instead of class names to conveniently assign middleware to routes and groups.
     *
     * @var array<string, class-string|string>
     */
    protected $middlewareAliases = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        // 'auth.session' => \Illuminate\Session\Middleware\AuthenticateSession::class, // Removed for custom session handler
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class,
        'precognitive' => \Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests::class,
        'signed' => \App\Http\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        // DISABLED 2025-09-14: RsxMiddleware removed as RSX routing now handled via 404 exception handler
        // To re-enable: rename RsxMiddleware.php.disabled back to .php and declare it in
        // config('rsx.middleware') - 'aliases' => ['rsx' => ...] - never by editing this file.
    ];

    /**
     * Bootstrap the application, then fold in the application's declared middleware.
     *
     * The rsx config merge happens INSIDE parent::bootstrap() (Rsx_Framework_Provider
     * registers under the RegisterProviders bootstrapper), so config('rsx.middleware')
     * is only readable after the parent call.
     */
    public function bootstrap(): void
    {
        parent::bootstrap();

        $this->__merge_configured_middleware((array) config('rsx.middleware', []));
    }

    /**
     * Append the middleware declared in config('rsx.middleware') to this kernel.
     *
     * APPEND-ONLY by construction: entries land at the END of the framework stack,
     * of a framework group, or beside the framework aliases. There is no spelling
     * that reorders or removes framework middleware.
     *
     * Every declared class is validated LOUDLY (a typo must not silently do nothing).
     * Declaring something already present is a silent no-op.
     *
     * @param array $config The 'middleware' config block: 'global', 'aliases',
     *                      plus one key per existing middleware group ('web', 'api').
     */
    protected function __merge_configured_middleware(array $config): void
    {
        if (empty($config)) {
            return;
        }

        foreach ($config as $key => $entries) {
            if ($key === 'aliases') {
                $this->__merge_configured_aliases((array) $entries);
                continue;
            }

            if ($key === 'global') {
                foreach ((array) $entries as $middleware) {
                    $this->__assert_middleware_class($middleware, 'rsx.middleware.global');

                    if (!in_array($middleware, $this->middleware, true)) {
                        $this->middleware[] = $middleware;
                    }
                }
                continue;
            }

            if (!array_key_exists($key, $this->middlewareGroups)) {
                throw new RuntimeException(
                    "config('rsx.middleware') declares unknown middleware group '{$key}'. "
                    . 'Valid keys are: global, aliases, ' . implode(', ', array_keys($this->middlewareGroups))
                    . '. See: php artisan rsx:man config_rsx'
                );
            }

            foreach ((array) $entries as $middleware) {
                $this->__assert_middleware_class($middleware, "rsx.middleware.{$key}");

                if (!in_array($middleware, $this->middlewareGroups[$key], true)) {
                    $this->middlewareGroups[$key][] = $middleware;
                }
            }
        }

        // The router received its copy of the groups/aliases in the constructor,
        // long before this ran.
        $this->syncMiddlewareToRouter();
    }

    /**
     * Merge declared middleware aliases. An alias already bound to a DIFFERENT class
     * is a collision and throws naming both classes - silently shadowing a framework
     * alias would break every route that uses it, somewhere else entirely.
     *
     * @param array $aliases alias => class map
     */
    private function __merge_configured_aliases(array $aliases): void
    {
        foreach ($aliases as $alias => $middleware) {
            if (!is_string($alias) || $alias === '') {
                throw new RuntimeException(
                    "config('rsx.middleware.aliases') must be an alias => class map; "
                    . 'got a non-string key. See: php artisan rsx:man config_rsx'
                );
            }

            $this->__assert_middleware_class($middleware, "rsx.middleware.aliases.{$alias}");

            if (array_key_exists($alias, $this->middlewareAliases)) {
                if ($this->middlewareAliases[$alias] === $middleware) {
                    continue;
                }

                throw new RuntimeException(
                    "config('rsx.middleware.aliases') declares alias '{$alias}' as {$middleware}, "
                    . "but it is already bound to {$this->middlewareAliases[$alias]}. "
                    . 'Aliases are append-only; pick a different alias. See: php artisan rsx:man config_rsx'
                );
            }

            $this->middlewareAliases[$alias] = $middleware;
        }
    }

    /**
     * A declared middleware entry must be a non-empty string naming a real class.
     * The optional ':parameters' suffix Laravel supports is stripped before the check.
     *
     * @param mixed  $middleware The declared entry
     * @param string $config_key The config path it was declared at, for the error text
     */
    private function __assert_middleware_class($middleware, string $config_key): void
    {
        if (!is_string($middleware) || $middleware === '') {
            throw new RuntimeException(
                "config('{$config_key}') declares a middleware entry that is not a class-name string. "
                . 'See: php artisan rsx:man config_rsx'
            );
        }

        $class = explode(':', $middleware, 2)[0];

        if (!class_exists($class)) {
            throw new RuntimeException(
                "config('{$config_key}') declares middleware {$class}, which does not exist. "
                . 'See: php artisan rsx:man config_rsx'
            );
        }
    }
}
