<?php
/**
 * THIS FILE IS OWNED BY THE FRAMEWORK.
 *
 * Any change you make here is OVERWRITTEN on the next framework update
 * (php artisan rsx:framework:pull hard-syncs it, and a local edit is refused
 * by the tamper gate until you drop it). Do not edit this file.
 *
 * To add your own HTTP middleware, declare it in config - never here:
 *
 *     // rsx/resource/config/rsx.php
 *     'middleware' => [
 *         'global' => [\App\Http\Middleware\My_Middleware::class],
 *     ],
 *
 * The declaration is APPEND-ONLY: your middleware always runs AFTER the
 * framework stack, and nothing in config can reorder or remove a framework
 * middleware. If you genuinely need that, file a framework change request.
 *
 * THERE IS NO LARAVEL ROUTER IN THE REQUEST PATH. The kernel's router destination
 * is Rsx_Front_Controller::handle(): every request that survives the global
 * middleware is dispatched by RSX, and no Laravel route - a vendor package's
 * included - is reachable. So there are no route middleware groups ('web', 'api')
 * and no middleware aliases: nothing would ever run them.
 *
 * See: php artisan rsx:man config_rsx
 *
 * CODING CONVENTION:
 * snake_case for variable_names and function_names. The camelCase properties
 * below are Laravel's, inherited from Illuminate\Foundation\Http\Kernel.
 */

namespace App\Http;

use RuntimeException;
use Illuminate\Foundation\Http\Kernel as HttpKernel;
use App\RSpade\Core\Dispatch\Rsx_Front_Controller;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array<int, class-string|string>
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Illuminate\Http\Middleware\HandleCors::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        // RSX Framework: Empty strings should remain empty strings, not be converted to null
        // This allows developers to distinguish between "no value provided" and "empty value provided"
        // \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        // Custom RSX middleware
        \App\Http\Middleware\PlaywrightTestMode::class,
    ];

    /**
     * The router destination: every request goes to the RSX front controller. Laravel's
     * router is never consulted.
     *
     * @return \Closure
     */
    protected function dispatchToRouter()
    {
        return function ($request) {
            $this->app->instance('request', $request);

            return Rsx_Front_Controller::handle($request);
        };
    }

    /**
     * Bootstrap the application, then fold in the application's declared middleware.
     *
     * The rsx config merge happens INSIDE parent::bootstrap() (Rsx_Framework_Provider
     * registers under the RegisterProviders bootstrapper), so config('rsx.middleware')
     * is only readable after the parent call.
     */
    public function bootstrap(): void
    {
        parent::bootstrap();

        $this->__merge_configured_middleware((array) config('rsx.middleware', []));
    }

    /**
     * Append the middleware declared in config('rsx.middleware') to this kernel.
     *
     * APPEND-ONLY by construction: entries land at the END of the framework stack. There
     * is no spelling that reorders or removes framework middleware.
     *
     * 'global' is the only key. 'web', 'api' and 'aliases' declared route middleware,
     * which RSX never runs (the router is not in the request path), so a non-empty one
     * throws rather than silently doing nothing; any other key is a typo and throws too.
     * Every declared class is validated LOUDLY. Declaring something already present is a
     * silent no-op.
     *
     * @param array $config The 'middleware' config block
     */
    protected function __merge_configured_middleware(array $config): void
    {
        foreach ($config as $key => $entries) {
            if ($key === 'global') {
                foreach ((array) $entries as $middleware) {
                    $this->__assert_middleware_class($middleware, 'rsx.middleware.global');

                    if (!in_array($middleware, $this->middleware, true)) {
                        $this->middleware[] = $middleware;
                    }
                }
                continue;
            }

            if (in_array($key, ['web', 'api', 'aliases'], true)) {
                if (empty($entries)) {
                    continue;
                }

                throw new RuntimeException(
                    "config('rsx.middleware.{$key}') declares route middleware, which never runs: RSX "
                    . "requests do not pass through Laravel's router, so there are no middleware groups "
                    . "or aliases. Declare the middleware under 'global' (it then wraps every request) and "
                    . 'return early for the requests it does not concern. See: php artisan rsx:man config_rsx'
                );
            }

            throw new RuntimeException(
                "config('rsx.middleware') declares unknown key '{$key}'. The only key is 'global'. "
                . 'See: php artisan rsx:man config_rsx'
            );
        }
    }

    /**
     * A declared middleware entry must be a non-empty string naming a real class.
     * The optional ':parameters' suffix Laravel supports is stripped before the check.
     *
     * @param mixed  $middleware The declared entry
     * @param string $config_key The config path it was declared at, for the error text
     */
    private function __assert_middleware_class($middleware, string $config_key): void
    {
        if (!is_string($middleware) || $middleware === '') {
            throw new RuntimeException(
                "config('{$config_key}') declares a middleware entry that is not a class-name string. "
                . 'See: php artisan rsx:man config_rsx'
            );
        }

        $class = explode(':', $middleware, 2)[0];

        if (!class_exists($class)) {
            throw new RuntimeException(
                "config('{$config_key}') declares middleware {$class}, which does not exist. "
                . 'See: php artisan rsx:man config_rsx'
            );
        }
    }
}
