<?php

namespace Rsx\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use App\RSpade\Core\Database\Models\Rsx_Site_Model_Abstract;
use App\RSpade\Core\Models\Portal_User_Model;
use App\RSpade\Core\Models\User_Model;
use Rsx\Models\Client_Department_Model;
use Rsx\Models\Client_Model;
/**
 * _AUTO_GENERATED_ Database type hints - do not edit manually
 * Table: contacts
 *
 * @property int $id
 * @property int $site_id
 * @property int $client_id
 * @property string $first_name
 * @property string $last_name
 * @property string $title
 * @property int $client_department_id
 * @property string $email
 * @property string $email_secondary
 * @property string $phone_work
 * @property string $phone_cell
 * @property string $phone_other
 * @property string $address
 * @property string $city
 * @property string $state
 * @property string $zip
 * @property int $reports_to_contact_id
 * @property int $is_active
 * @property int $priority
 * @property string $notes
 * @property int $created_by_id
 * @property int $created_by_type
 * @property int $owner_user_id
 * @property string $created_at
 * @property string $updated_at
 * @property int $updated_by_id
 * @property int $updated_by_type
 * @property string $deleted_at
 * @property int $deleted_by_id
 * @property int $deleted_by_type
 *
 * @property-read string $priority__label
 * @property-read string $priority__constant
 *
 * @method static array priority__enum() Get all enum definitions with full metadata
 * @method static array priority__enum_select() Get [{value, label}] array for dropdowns
 * @method static array priority__enum_labels() Get simple id => label map
 * @method static array priority__enum_ids() Get array of all valid enum IDs
 *
 * @mixin \Eloquent
 */
#[Auth('is_logged_in')]
class Contact_Model extends Rsx_Site_Model_Abstract
{
    /**
     * UNBOUNDED: this table's row count grows with customer activity, not with the
     * codebase, so no reader may assume the set is small.
     * Contacts multiply by client - a single large client can hold tens of thousands.
     *
     * A DECLARATION, not a runtime gate - a small, well-narrowed query here is still
     * fine. It marks the tables where a bare ->get() deserves a second look, and where
     * ->result_set() is usually the right answer. See the "Do The Whole Job" section
     * of CLAUDE.md.
     *
     * @var bool
     */
    public static $unbounded = true;

    /**
     * _AUTO_GENERATED_ Enum constants
     */
    const PRIORITY_LOW = 1;
    const PRIORITY_MEDIUM = 2;
    const PRIORITY_HIGH = 3;
    const PRIORITY_URGENT = 4;

    use SoftDeletes;

    protected $table = 'contacts';
    protected $fillable = []; // No mass assignment - always explicit

    // Realtime: this model emits its own change AND (via #[Realtime_Touch] on client())
    // touches its parent client so the client's contacts result set (Clients_View contacts
    // tab) live-refreshes on edit — including bulk builder writes.
    public static $realtime = true;

    /**
     * Revision history: a contact's own writes are recorded, AND (via #[Revision_Parent]
     * on client()) filed under the parent client's history as well.
     */
    public static $revisions = true;

    public static $enums = [
        'priority' => [
            1 => ['constant' => 'PRIORITY_LOW', 'label' => 'Low', 'badge' => 'bg-secondary'],
            2 => ['constant' => 'PRIORITY_MEDIUM', 'label' => 'Medium', 'badge' => 'bg-primary'],
            3 => ['constant' => 'PRIORITY_HIGH', 'label' => 'High', 'badge' => 'bg-warning'],
            4 => ['constant' => 'PRIORITY_URGENT', 'label' => 'Urgent', 'badge' => 'bg-danger'],
        ],
    ];

    // Enum constants (auto-generated by rsx:constants:regenerate)

    /**
     * Get formatted contact ID for display
     * @return string
     */
    public function contact_id_formatted()
    {
        return '#CO' . str_pad($this->id, 3, '0', STR_PAD_LEFT);
    }

    /**
     * Get full name from first and last name
     * @return string
     */
    public function full_name()
    {
        return trim($this->first_name . ' ' . $this->last_name);
    }

    /**
     * Relationships
     */
    #[Relationship]
    #[Ajax_Endpoint_Model_Fetch]
    #[Realtime_Touch]
    #[Revision_Parent]
    public function client()
    {
        return $this->belongsTo(Client_Model::class, 'client_id');
    }

    #[Relationship]
    #[Ajax_Endpoint_Model_Fetch]
    public function department()
    {
        return $this->belongsTo(Client_Department_Model::class, 'client_department_id');
    }

    #[Relationship]
    #[Ajax_Endpoint_Model_Fetch]
    public function reports_to()
    {
        return $this->belongsTo(Contact_Model::class, 'reports_to_contact_id');
    }

    #[Relationship]
    #[Ajax_Endpoint_Model_Fetch]
    public function direct_reports()
    {
        return $this->hasMany(Contact_Model::class, 'reports_to_contact_id');
    }

    #[Relationship]
    public function owner()
    {
        return $this->belongsTo(User_Model::class, 'owner_user_id');
    }

    /**
     * Accessors
     */
    public function get_full_name_attribute()
    {
        return trim($this->first_name . ' ' . $this->last_name);
    }

    /**
     * Resolve the client-portal account linked to this contact: first by the
     * portal_users.contact_id link, then by matching email within the same site.
     * Returns null when the contact has no portal access. Used by the staff
     * "View as Client" impersonation affordance.
     *
     * @return \App\RSpade\Core\Models\Portal_User_Model|null
     */
    public function resolve_portal_user()
    {
        $portal_user = Portal_User_Model::where('site_id', $this->site_id)
            ->where('contact_id', $this->id)
            ->first();

        if (!$portal_user && !empty($this->email)) {
            $portal_user = Portal_User_Model::find_by_email((int) $this->site_id, $this->email);
        }

        return $portal_user;
    }

    /**
     * The id of the client-portal account linked to this contact, or null.
     * Method name matches the fetch() payload key (see resolve_portal_user()).
     *
     * @return int|null
     */
    public function portal_user_id()
    {
        $portal_user = $this->resolve_portal_user();

        return $portal_user ? $portal_user->id : null;
    }

    /**
     * Ajax model fetch - allows JavaScript to load contact records.
     *
     * Surface gating is declarative: the class-level #[Auth('is_logged_in')] is evaluated
     * at the ORM seam BEFORE this body runs, and a denial returns the same generic
     * "not found" a missing row does. Record-level rules (ownership, membership scoping,
     * record state) belong HERE, returning false. This model has none beyond the site
     * scope the site-model abstract already applies.
     */
    #[Ajax_Endpoint_Model_Fetch]
    public static function fetch($id)
    {
        $contact = static::find($id);

        if (!$contact) {
            return false;
        }

        // Start with model's toArray() to get __MODEL and base data
        $data = $contact->toArray();

        // Augment with model methods (key must match method name)
        $data['contact_id_formatted'] = $contact->contact_id_formatted();
        $data['full_name'] = $contact->full_name();

        // Portal access: expose the linked portal user id (if any) so staff can
        // "View as Client" - impersonate the read-only portal experience.
        $data['portal_user_id'] = $contact->portal_user_id();

        return $data;
    }
}