<?php

namespace App\RSpade\Tests\StorageIsolation\Php;

use Illuminate\Support\Facades\DB;
use App\RSpade\Core\Files\File_Attachment_Model;
use App\RSpade\Core\Files\File_Preview_Controller;
use App\RSpade\Core\Files\File_Storage_Model;
use App\RSpade\Core\Files\Rsx_File_Paths;
use App\RSpade\Core\Session\Session;
use App\RSpade\Core\Testing\Rsx_Test_Abstract;

/**
 * File-storage isolation (backlog B-38).
 *
 * The whole file subsystem (content-addressed blob store, thumbnail cache, rendition cache)
 * resolves its on-disk locations through Rsx_File_Paths. In default mode those paths are
 * exactly the storage_path('...') layout. During a test run the runner
 * (Rsx_Test_Command) sets the INTERNAL config key rsx.files.storage_root to
 * storage/rsx-tmp/test-storage, so a test-DB attachment delete can never unlink a blob shared
 * with the developer database.
 *
 * These tests execute INSIDE a run, where the runner has already set the override - so the live
 * isolation proof observes the real production configuration, not a mock.
 */
class Storage_Isolation_Test extends Rsx_Test_Abstract
{
    /**
     * Resolve a seeded site id and set it as the session site so the site FK + site-scoped save
     * hook on _file_attachments are satisfied in the CLI test harness.
     *
     * @return int
     */
    private static function __site_id(): int
    {
        $id = (int) DB::selectOne('SELECT id FROM sites ORDER BY id LIMIT 1')->id;
        Session::set_site_id($id);
        return $id;
    }

    /**
     * Mirror the plain-ingest path (store_blob + a linked attachment) from unique generated bytes,
     * avoiding create_from_upload's HTTP-session dependency.
     *
     * @param string $bytes
     * @return File_Attachment_Model
     */
    private static function __make_plain(string $bytes): File_Attachment_Model
    {
        $tmp = tempnam(sys_get_temp_dir(), 'rsx_iso_');
        file_put_contents($tmp, $bytes);
        $storage = File_Storage_Model::store_blob($tmp);
        @unlink($tmp);

        $a = new File_Attachment_Model();
        $a->key = File_Attachment_Model::generate_key();
        $a->file_storage_id = $storage->id;
        $a->file_name = 'iso.bin';
        $a->file_extension = 'bin';
        $a->mime_type = 'application/octet-stream';
        $a->file_size = $storage->size;
        $a->file_type_id = File_Attachment_Model::determine_file_type('application/octet-stream');
        $a->site_id = static::__site_id();
        $a->save();

        return $a;
    }

    /**
     * Default mode (no override) roots must equal storage_path('...') exactly, so relocation
     * NEVER changes normal-deployment paths. We temporarily clear the run's override to observe
     * default behavior, then restore it.
     */
    public static function test_default_mode_paths_are_exactly_storage_path()
    {
        $saved = config('rsx.files.storage_root');

        try {
            config(['rsx.files.storage_root' => null]);

            static::__assert_equals(storage_path(), Rsx_File_Paths::storage_root(), 'default storage_root is storage_path()');
            static::__assert_equals(storage_path('uploads'), Rsx_File_Paths::blob_root(), 'default blob_root is storage_path(uploads)');
            static::__assert_equals(storage_path('rsx-thumbnails'), Rsx_File_Paths::thumbnails_root(), 'default thumbnails_root is storage_path(rsx-thumbnails)');
            static::__assert_equals(storage_path('rsx-renditions'), Rsx_File_Paths::renditions_root(), 'default renditions_root is storage_path(rsx-renditions)');

            // A storage record's full path must equal storage_path(get_storage_path()).
            $m = new File_Storage_Model();
            $m->hash = 'abc123def456abc123def456';
            static::__assert_equals(
                storage_path($m->get_storage_path()),
                $m->get_full_path(),
                'get_full_path equals storage_path(get_storage_path) in default mode'
            );
        } finally {
            config(['rsx.files.storage_root' => $saved]);
        }
    }

    /**
     * With the run's override active, every root lives under storage/rsx-tmp/test-storage.
     */
    public static function test_override_relocates_roots()
    {
        $override = config('rsx.files.storage_root');
        static::__assert_not_empty($override, 'the test runner set an override storage root for this run');

        $expected_root = storage_path('rsx-tmp/test-storage');
        static::__assert_equals($expected_root, Rsx_File_Paths::storage_root(), 'override root is storage/rsx-tmp/test-storage');
        static::__assert_equals($expected_root . '/uploads', Rsx_File_Paths::blob_root(), 'blob_root under the override');
        static::__assert_equals($expected_root . '/rsx-thumbnails', Rsx_File_Paths::thumbnails_root(), 'thumbnails_root under the override');
        static::__assert_equals($expected_root . '/rsx-renditions', Rsx_File_Paths::renditions_root(), 'renditions_root under the override');
    }

    /**
     * THE B-38 proof: a blob authored during a test run is written under the test root and NOT the
     * real store, and deleting the attachment (the deleted-hook that unlinks the last-reference
     * blob) removes the file from the test root only - the real store is never touched.
     */
    public static function test_blob_written_and_deleted_only_in_test_root()
    {
        // Unique bytes -> a hash that cannot pre-exist in either store.
        $bytes = 'rsx-b38-isolation-' . uniqid('', true) . '-' . random_hash(16);
        $a = static::__make_plain($bytes);
        $storage = $a->file_storage;
        $hash = $storage->hash;

        $test_path = $storage->get_full_path();
        $dir1 = substr($hash, 0, 2);
        $dir2 = substr($hash, 2, 2);
        $real_path = storage_path("uploads/{$dir1}/{$dir2}/{$hash}");

        // Written into the isolated test root, provably NOT the real developer store.
        static::__assert_contains('/rsx-tmp/test-storage/uploads/', $test_path, 'blob resolves under the test root');
        static::__assert_true(file_exists($test_path), 'blob written to the test root');
        static::__assert_false(file_exists($real_path), 'blob does NOT exist in the real developer store');

        // Permanently destroying the last-reference attachment unlinks the blob (via the
        // disposal service's release path) - test root only. force_destroy(), not delete():
        // a plain delete() soft-deletes into retention and the blob survives by design.
        $storage_id = $storage->id;
        $a->force_destroy();

        static::__assert_false(file_exists($test_path), 'blob removed from the test root on destroy');
        static::__assert_null(File_Storage_Model::find($storage_id), 'orphaned storage row released on destroy');
        static::__assert_false(file_exists($real_path), 'the real developer store was never touched');
    }

    /**
     * Thumbnail and rendition path derivation (the cache-path seams used by the controllers) honor
     * the override without needing to actually render.
     */
    public static function test_thumbnail_and_rendition_paths_honor_override()
    {
        $root = storage_path('rsx-tmp/test-storage');

        // Thumbnail cache path seam.
        $cache_path = \App\RSpade\Core\Files\File_Attachment_Controller::_get_cache_path('preset', 'x_1x1_deadbeef_png.webp');
        static::__assert_equals($root . '/rsx-thumbnails/preset/x_1x1_deadbeef_png.webp', $cache_path, 'thumbnail cache path honors the override');

        // Rendition cache path seam (content-addressed on the blob hash).
        $storage = new File_Storage_Model();
        $storage->hash = 'feed0000feed0000feed0000';
        $rendition_path = File_Preview_Controller::rendition_cache_path($storage);
        static::__assert_equals($root . '/rsx-renditions/feed0000feed0000feed0000.pdf', $rendition_path, 'rendition cache path honors the override');
    }
}
