// @FILE-SUBCLASS-01-EXCEPTION

/**
 * Base class for JavaScript ORM models
 *
 * Provides core functionality for fetching records from backend PHP models.
 * All model stubs generated by the manifest extend this base class.
 *
 * Example usage:
 *   // Fetch single record
 *   const user = await User_Model.fetch(123);
 *
 *   // Create instance with data
 *   const user = new User_Model({id: 1, name: 'John'});
 *
 * @Instantiatable
 */
class Rsx_Js_Model {
    // Client-side fetch cache: Map<"ModelName:id", Promise<model>>
    // Reset on SPA navigation, manual reset via orm_cache_reset()
    static _fetch_cache = new Map();

    // ========================================================================
    // ORM FETCH BATCHER
    //
    // Every fetch()/fetch_or_null() used to be its own HTTP request, so a page
    // rendering N records paid N round trips. These three maps turn all the lookups
    // issued during one synchronous turn into ONE request per model. Callers observe
    // nothing but speed: each fetch() still behaves as an individual request with an
    // individual response, and transport errors still reach exactly the caller that
    // made the failing lookup.
    //
    // _orm_pending  "Model:id" -> {promise, resolve, reject}. ONE entry per outstanding
    //               lookup. An entry is JOINABLE from the moment it is created until the
    //               response for its chunk is distributed - that is the dedup window: two
    //               fetches of the same record that overlap share one wire slot and one
    //               result object, while a fetch issued AFTER the previous one resolved
    //               starts a fresh cycle and hits the server again. (Caching across that
    //               boundary is fetch_cached()'s job, deliberately opt-in.)
    //               fetch() and fetch_or_null() share the SAME entry - the wire answer is
    //               identical (present or absent); only the local reaction differs.
    //
    // _orm_queue    "Model" -> Set of ids enqueued but not yet sent. A Set, so a repeated
    //               id in one turn is requested once.
    //
    // _orm_flush_scheduled  Exactly one flush callback may be outstanding at a time.
    // ========================================================================
    static _orm_pending = new Map();
    static _orm_queue = new Map();
    static _orm_flush_scheduled = false;

    /**
     * Constructor - Initialize model instance with data
     *
     * @param {Object} data - Key-value pairs to populate the model
     */
    constructor(data = {}) {
        // __MODEL SYSTEM: Enables automatic ORM instantiation when fetching from PHP models.
        // PHP models add "__MODEL": "ClassName" to JSON, JavaScript uses it to create proper instances.
        // This provides typed model objects instead of plain JSON, with methods and type checking.

        // This constructor filters out the __MODEL marker that was used to identify which class
        // to instantiate, keeping only the actual data properties on the instance.
        const { __MODEL, ...modelData } = data;

        // Check for property conflicts before assignment
        const modelName = __MODEL || this.constructor.name;
        for (const key in modelData) {
            if (key in this) {
                if (typeof this[key] === 'function') {
                    throw new Error(
                        `Model property conflict: "${key}" from server response would overwrite ` +
                        `a method on ${modelName}. Check the PHP model's fetch() or toArray() method ` +
                        `to see if "${key}" should be excluded or renamed. If the JS method ${key}() ` +
                        `is computing a value the server now provides, remove the JS method.`
                    );
                } else {
                    throw new Error(
                        `Model property conflict: "${key}" already exists on ${modelName} ` +
                        `and would be overwritten by server response data.`
                    );
                }
            }
        }

        Object.assign(this, modelData);
    }

    /**
     * Fetch a record from the backend model
     *
     * This method mirrors the PHP Model::fetch() functionality.
     * The backend model must have a fetch() method with the
     * #[Ajax_Endpoint_Model_Fetch] annotation to be callable.
     *
     * Throws an error if the record is not found or access is denied.
     * Use fetch_or_null() if you want null instead of an exception.
     *
     * The lookup rides the batcher (see the maps at the top of this class), so calling
     * this for twenty records in one turn costs one request, not twenty. That is
     * invisible here: this call resolves with its own record, or throws its own error.
     *
     * @param {number} id - ID to fetch
     * @returns {Promise} - Model instance
     * @throws {Error} - If record not found or access denied (code Ajax.ERROR_NOT_FOUND)
     */
    static async fetch(id) {
        const CurrentClass = this;
        // Get the PHP model name from the static __MODEL property
        // This allows Base_Project_Model to correctly identify as "Project_Model" to PHP
        const modelName = CurrentClass.__MODEL || CurrentClass.name;
        const record_id = Rsx_Js_Model._orm_normalize_id(modelName, id);

        const outcome = await Rsx_Js_Model._orm_enqueue(modelName, record_id);

        if (!outcome.found) {
            // Byte-identical to what the server used to send for a missing/denied/refused
            // record. The server no longer distinguishes them on the wire (an id is simply
            // absent from the response), so this is where the distinction between "throw"
            // and "return null" is made - by which method the caller chose.
            const error = new Error('Record not found');
            error.code = Ajax.ERROR_NOT_FOUND;
            error.metadata = {};
            throw error;
        }

        // The record was hydrated by the Ajax layer (Ajax.js calls
        // _instantiate_models_recursive over the whole response, nested records included).

        // Warm fetch cache for subsequent fetch_cached() calls
        Rsx_Js_Model._fetch_cache.set(`${modelName}:${record_id}`, Promise.resolve(outcome.record));

        return outcome.record;
    }

    /**
     * Fetch record from the backend model, returning null if not found
     *
     * Same as fetch() but returns null instead of throwing an error
     * when the record doesn't exist or access is denied.
     *
     * Use this when you're not sure if the record exists and want
     * to handle the "not found" case gracefully without try/catch.
     *
     * Shares a wire slot with fetch(): both ask the server the same question, and an
     * overlapping fetch() and fetch_or_null() for the same record produce one request.
     * A transport or batch-level failure still THROWS here - or_null is about a missing
     * record, never about a failed request.
     *
     * @param {number} id - ID to fetch
     * @returns {Promise} - Model instance or null if not found
     */
    static async fetch_or_null(id) {
        const CurrentClass = this;
        const modelName = CurrentClass.__MODEL || CurrentClass.name;
        const record_id = Rsx_Js_Model._orm_normalize_id(modelName, id);

        const outcome = await Rsx_Js_Model._orm_enqueue(modelName, record_id);

        if (!outcome.found) {
            return null;
        }

        // Warm fetch cache on successful fetch (don't cache nulls)
        Rsx_Js_Model._fetch_cache.set(`${modelName}:${record_id}`, Promise.resolve(outcome.record));

        return outcome.record;
    }

    /**
     * Normalize and validate a record id for the batcher.
     *
     * The id is the identity half of a pending-entry key, so "5" and 5 must produce the
     * same key or the two callers would each open their own wire slot for one record.
     * A non-numeric id is a programming error, not a missing record: it fails loud with
     * the validation code the server used to answer with.
     *
     * @param {string} model_name
     * @param {*} id
     * @returns {number}
     */
    static _orm_normalize_id(model_name, id) {
        if (!is_numeric(id)) {
            const error = new Error(`${model_name}.fetch() requires a numeric record id, got: ${str(id)}`);
            error.code = Ajax.ERROR_VALIDATION;
            error.metadata = {};
            throw error;
        }

        return int(id);
    }

    /**
     * Join the outstanding lookup for (model, id), or open one and queue it.
     *
     * @param {string} model_name
     * @param {number} record_id
     * @returns {Promise<{found: boolean, record: *}>} Resolves with the outcome for THIS
     *          id; rejects with the batch's error if the request itself failed.
     */
    static _orm_enqueue(model_name, record_id) {
        const key = `${model_name}:${record_id}`;
        const existing = Rsx_Js_Model._orm_pending.get(key);

        // Joinable until its response is distributed - see the dedup-window note above.
        if (existing) {
            return existing.promise;
        }

        let entry_resolve;
        let entry_reject;
        const promise = new Promise((resolve, reject) => {
            entry_resolve = resolve;
            entry_reject = reject;
        });

        Rsx_Js_Model._orm_pending.set(key, { promise: promise, resolve: entry_resolve, reject: entry_reject });

        if (!Rsx_Js_Model._orm_queue.has(model_name)) {
            Rsx_Js_Model._orm_queue.set(model_name, new Set());
        }
        Rsx_Js_Model._orm_queue.get(model_name).add(record_id);

        Rsx_Js_Model._orm_schedule_flush();

        return promise;
    }

    /**
     * Ensure exactly one flush is scheduled.
     *
     * setTimeout(0) is the flush SCHEDULER, not a deadline (owner ruling 2026-08-13;
     * same choice the transport batcher makes - Ajax.DEBOUNCE_MS is 0). It defers the
     * request until every synchronously-running piece of code - a template rendering
     * twenty rows, a component's on_load, a Promise.all - has finished enqueueing its
     * lookups, so they all leave in one request. Nothing is being given a time budget:
     * the callback runs on the next macrotask whatever else is happening, and the
     * framework's no-timeout mandate is about deadlines imposed on work, not about
     * scheduling when work starts.
     *
     * NOT requestAnimationFrame: rAF does not fire in a hidden tab, so a background
     * tab's realtime-driven refetches would queue up and never be sent.
     */
    static _orm_schedule_flush() {
        if (Rsx_Js_Model._orm_flush_scheduled) {
            return;
        }

        Rsx_Js_Model._orm_flush_scheduled = true;
        setTimeout(() => Rsx_Js_Model._orm_flush(), 0);
    }

    /**
     * Send everything queued, one request per model per chunk of ids.
     */
    static _orm_flush() {
        // Cleared FIRST: a lookup enqueued while this flush is being processed belongs to
        // the NEXT request and must be able to schedule its own tick.
        Rsx_Js_Model._orm_flush_scheduled = false;

        const queued = Rsx_Js_Model._orm_queue;
        Rsx_Js_Model._orm_queue = new Map();

        // The server REFUSES a request carrying more ids than this, so the client is what
        // splits a large set. One number, injected from rsx.model_fetch.batch_max_ids.
        const chunk_size = window.rsxapp.model_fetch.batch_max_ids;

        for (const [model_name, id_set] of queued) {
            const ids = Array.from(id_set);

            for (let offset = 0; offset < ids.length; offset += chunk_size) {
                Rsx_Js_Model._orm_dispatch_chunk(model_name, ids.slice(offset, offset + chunk_size));
            }
        }
    }

    /**
     * One request: fetch these ids of this model, then hand each waiting caller its own
     * outcome.
     *
     * An id PRESENT in the response resolved; an id ABSENT did not (it does not exist,
     * the model's fetch() refused it, or the surface's gates denied this caller - the
     * server deliberately reports all three identically, so a prober learns nothing).
     * A failed request rejects every caller in the chunk with the same error object,
     * which is exactly what each of them would have seen making the call alone.
     *
     * @param {string} model_name
     * @param {Array<number>} ids
     */
    static async _orm_dispatch_chunk(model_name, ids) {
        let records = null;
        let failure = null;

        try {
            const response = await Orm_Controller.fetch({ model: model_name, ids: ids });
            records = response.records;
        } catch (e) {
            failure = e;
        }

        for (const id of ids) {
            const key = `${model_name}:${id}`;
            const entry = Rsx_Js_Model._orm_pending.get(key);

            // The dedup window closes here: a fetch issued from now on opens a new entry.
            Rsx_Js_Model._orm_pending.delete(key);

            if (failure !== null) {
                entry.reject(failure);
                continue;
            }

            const record = records[String(id)];
            entry.resolve(record === undefined ? { found: false } : { found: true, record: record });
        }
    }

    /**
     * Fetch record using in-memory cache
     *
     * Returns cached result if available, otherwise calls fetch() and caches the result.
     * Stores promises so concurrent calls for the same model/id share a single backend
     * request. Cache automatically resets on SPA navigation.
     *
     * Intended for non-critical display data (names, labels, log history) where freshness
     * is not essential. Do NOT use for data that must reflect recent edits.
     *
     * @param {number} id - ID to fetch
     * @returns {Promise} - Model instance (from cache or fresh fetch)
     * @throws {Error} - If record not found or access denied
     */
    static async fetch_cached(id) {
        const CurrentClass = this;
        const modelName = CurrentClass.__MODEL || CurrentClass.name;
        const cache_key = `${modelName}:${id}`;

        if (Rsx_Js_Model._fetch_cache.has(cache_key)) {
            return Rsx_Js_Model._fetch_cache.get(cache_key);
        }

        // Store the promise itself - concurrent calls for same model/id
        // await the same promise (single backend request)
        const promise = CurrentClass.fetch(id);
        Rsx_Js_Model._fetch_cache.set(cache_key, promise);

        try {
            const result = await promise;
            return result;
        } catch (e) {
            // Failed fetches removed from cache so next attempt retries
            Rsx_Js_Model._fetch_cache.delete(cache_key);
            throw e;
        }
    }

    /**
     * Reset the ORM fetch cache
     *
     * Called automatically on SPA navigation. Can also be called manually
     * after save operations to ensure subsequent fetch_cached() calls
     * retrieve fresh data.
     *
     * @param {string} [model_name] - Clear specific model only (all IDs)
     * @param {number} [id] - Clear specific model+id (requires model_name)
     */
    static orm_cache_reset(model_name, id) {
        if (!model_name) {
            Rsx_Js_Model._fetch_cache.clear();
            return;
        }

        if (id !== undefined) {
            Rsx_Js_Model._fetch_cache.delete(`${model_name}:${id}`);
            return;
        }

        // Clear all entries for specific model
        const prefix = `${model_name}:`;
        for (const key of Rsx_Js_Model._fetch_cache.keys()) {
            if (key.startsWith(prefix)) {
                Rsx_Js_Model._fetch_cache.delete(key);
            }
        }
    }

    /**
     * Get the PHP model class name
     * Used internally for API calls
     *
     * @returns {string} The PHP model class name
     */
    static getModelName() {
        const CurrentClass = this;
        return CurrentClass.__MODEL || CurrentClass.name;
    }

    /**
     * Watch this model's record for changes (for NON-component code).
     *
     * Sugar over Rsx_Realtime.watch('Model_Changed_Topic', {model, id}, cb). Inside a
     * component use this.subscribe(Model_Class, id, cb) instead — that variant tracks the
     * handle and auto-stops on component destroy. This returns the raw {stop()} handle and
     * the caller is responsible for calling .stop().
     *
     * FAILS LOUD (throws) when the model has not opted into realtime emission (no baked-in
     * __REALTIME static — PHP `public static $realtime = true`). A subscription that could
     * never receive a message is a programming error, surfaced in every environment
     * (this check runs before watch()'s realtime-disabled no-op).
     *
     * @param {number} id - Record id to watch
     * @param {Function} cb - (data, meta) => void; data is null on a resync call (meta.resync)
     * @returns {Promise<{stop: Function}>} Handle — call .stop() to stop watching
     */
    static async watch_changes(id, cb) {
        if (!this.__REALTIME) {
            throw new Error(
                this.getModelName() + ' does not declare realtime emission — set ' +
                '`public static $realtime = true;` on the PHP model to watch its changes.'
            );
        }
        return Rsx_Realtime.watch('Model_Changed_Topic', { model: this.getModelName(), id: int(id) }, cb);
    }

    /**
     * Resolve a Class-Table Inheritance detail accessor (e.g. await record.party_company()).
     * Generated detail accessors on the model stub delegate here. The detail rides embedded
     * in this record's payload (under __details), so there is no network call. Wrong-type
     * access - the accessor does not match this record's discriminator value - throws locally.
     * Returns the hydrated detail model, or null when no persisted detail exists.
     *
     * @param {string} accessor - The detail accessor name (e.g. 'party_company')
     * @returns {Object|null} The hydrated detail model instance, or null
     */
    __resolve_detail(accessor) {
        const discriminator = this.constructor.__detail_discriminator;
        const value_to_accessor = this.constructor.__detail_value_to_accessor || {};
        const active = value_to_accessor[this[discriminator]];

        if (accessor !== active) {
            const detail_text = active
                ? `this record's detail is '${active}'`
                : `${discriminator}=${this[discriminator]} has no detail`;
            throw new Error(
                `${this.constructor.getModelName()} #${this.id}: detail accessor '${accessor}' is not valid for ` +
                `${discriminator}=${this[discriminator]} - ${detail_text}. Check the type before accessing type-specific fields.`
            );
        }

        const raw = (this.__details || {})[accessor];
        if (raw === null || raw === undefined) {
            return null;
        }

        return Rsx_Js_Model._instantiate_models_recursive(raw);
    }

    /**
     * Refresh this instance with latest data from server
     *
     * @returns {Promise} Updated instance or false if not found
     */
    async refresh() {
        const that = this;
        if (!that.id) {
            shouldnt_happen('Cannot refresh model without id property');
        }

        const fresh = await that.constructor.fetch(that.id);

        if (fresh === false) {
            return false;
        }

        // Update this instance with fresh data
        Object.assign(that, fresh);
        return that;
    }

    /**
     * Convert model instance to plain object
     * Useful for serialization or sending to APIs
     *
     * @returns {Object} Plain object representation
     */
    toObject() {
        const that = this;
        const obj = {};
        for (const key in that) {
            if (that.hasOwnProperty(key) && typeof that[key] !== 'function') {
                obj[key] = that[key];
            }
        }
        return obj;
    }

    /**
     * Convert model instance to JSON string
     *
     * @returns {string} JSON representation
     */
    toJSON() {
        const that = this;
        return JSON.stringify(that.toObject());
    }

    /**
     * Recursively instantiate ORM models in response data
     *
     * Looks for objects with __MODEL property and instantiates the appropriate
     * JavaScript model class from the Manifest registry.
     *
     * @param {*} data - The data to process (can be any type)
     * @returns {*} The data with ORM objects instantiated
     */
    static _instantiate_models_recursive(data) {
        // Handle null/undefined
        if (data === null || data === undefined) {
            return data;
        }

        // Handle arrays - recursively process each element
        if (Array.isArray(data)) {
            return data.map((item) => Rsx_Js_Model._instantiate_models_recursive(item));
        }

        // Handle objects
        if (typeof data === 'object') {
            // Check if this object has a __MODEL property
            if (data.__MODEL && typeof data.__MODEL === 'string') {
                // Look up the model class in the Manifest registry
                const ModelClass = Manifest.get_class_by_name(data.__MODEL);

                // If the model class exists and extends Rsx_Js_Model, instantiate it
                // Dynamic model resolution requires checking class existence - @JS-DEFENSIVE-01-EXCEPTION
                if (ModelClass && Manifest.js_is_subclass_of(ModelClass, Rsx_Js_Model)) {
                    return new ModelClass(data);
                }
            }

            // Recursively process all object properties
            const result = {};
            for (const key in data) {
                if (data.hasOwnProperty(key)) {
                    result[key] = Rsx_Js_Model._instantiate_models_recursive(data[key]);
                }
            }
            return result;
        }

        // Return primitive values as-is
        return data;
    }
}
