[program:php-fpm]
command=bash /usr/local/bin/rspade-retry-run php-fpm /usr/sbin/php-fpm8.4 -R -F -c /etc/php/8.4/fpm/php.ini -y /etc/php/8.4/fpm/php-fpm.conf
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startretries=999999
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
