[program:rsx-lockd]
command=bash /var/www/html/system/bin/rsx-lockd/lockd-run.sh
directory=/var/www/html
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/rsx-lockd.log
stderr_logfile=/var/log/supervisor/rsx-lockd-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5
killasgroup=true
stopasgroup=true
