<?php
/**
 * CODING CONVENTION:
 * This file follows the coding convention where variable_names and function_names
 * use snake_case (underscore_wherever_possible).
 */

namespace App\RSpade\Core\Codegen;

use PhpParser\Node;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitorAbstract;
use PhpParser\ParserFactory;
use RuntimeException;

/**
 * AST-guided, fence-safe rewriter for the auto-generated regions of model files.
 *
 * The model codegen command (rsx:constants:regenerate)
 * owns a small number of clearly delimited regions inside each model file:
 *
 *   Region A  - the pre-class docblock whose text contains `_AUTO_GENERATED_`.
 *   Region B1 - the post-brace "_AUTO_GENERATED_ Enum constants" docblock plus the
 *               contiguous run of `const` declarations it heads (the canonical home for
 *               enum constants).
 *   Region B2 - the "__AUTO_GENERATED:" / "__/AUTO_GENERATED" fenced pair and
 *               everything between the two markers (the OLD-FORMAT rsx:constants:regenerate
 *               home for enum constants). A B2 fence holding enum constants is migrated
 *               into a canonical B1 block in a single rewrite (removed, its constants
 *               re-emitted as B1) - never left in place alongside a fresh B1, which would
 *               declare every constant twice and fatal. An empty B2 fence is inert and
 *               left as-is.
 *
 * EVERY byte outside those regions is hand-written and must survive a regeneration
 * verbatim - including code sitting between the class opening brace and the first
 * fence (the exact spot a past regen silently destroyed a `public static $realtime`
 * declaration). See docs.dev/external_requests/2026_07_15_document_models_regen_clobbers_class_top.md
 *
 * This class provides:
 *   - strip_owned_regions(): removes ALL owned regions, returning only hand-written
 *     bytes. The self-check compares strip(original) against strip(candidate); if they
 *     differ, hand-written content was altered and the write is refused. This guarantee
 *     is mechanism-independent: it holds no matter how the candidate was produced.
 *   - rewrite(): the surgical in-place rewrite used by rsx:constants:regenerate, with
 *     the self-check embedded (throws on any mismatch).
 *   - assert_no_handwritten_change(): the standalone byte-exact self-check embedded in
 *     rewrite().
 *
 * Region detection is structural (php-parser), never regex on source. Any structural
 * surprise (class not found, duplicate/unbalanced markers, parse error) throws - the
 * caller must fail loud and skip the file, never best-effort-rewrite it.
 */
class Model_Codegen_Rewriter
{
    /**
     * Marker fragments. A pre-class docblock is owned when its text contains
     * SINGLE_UNDERSCORE_MARKER. The fenced const block is delimited by the two
     * FENCE markers (mutually exclusive substrings: colon vs. slash).
     */
    private const SINGLE_UNDERSCORE_MARKER = '_AUTO_GENERATED_';
    private const ENUM_CONSTANTS_MARKER = '_AUTO_GENERATED_ Enum constants';
    private const FENCE_OPEN_MARKER = '__AUTO_GENERATED:';
    private const FENCE_CLOSE_MARKER = '__/AUTO_GENERATED';

    protected static $parser = null;

    protected static function __parser()
    {
        if (static::$parser === null) {
            static::$parser = (new ParserFactory())->createForNewestSupportedVersion();
        }
        return static::$parser;
    }

    /**
     * Surgical in-place rewrite for rsx:constants:regenerate.
     *
     * Replaces (or inserts) Region A with $doc_block and the file's single
     * enum-constants region with $constants_block, leaving every other byte verbatim.
     *
     * The enum-constants region is EITHER the canonical Region B1 (an
     * `_AUTO_GENERATED_ Enum constants` docblock + const run) OR, on a file still in the
     * old fenced layout, a Region B2 fence pair whose content is
     * enum constants. When such a B2-constants fence is present it is MIGRATED in one pass:
     * its constants are owned/auto-generated by definition (they sit inside the fence), so
     * the fence is removed and the canonical B1 block is emitted in its place. This
     * guarantees exactly ONE set of constants (never the duplicate-const parse fatal that a
     * naive "insert B1, leave the old fence" rewrite produced). A B2 fence that is EMPTY
     * (constants already migrated) is left untouched - removing it would churn the file for
     * no gain. A B2 fence containing NON-constant content cannot be classified and throws:
     * fail loud, skip the file, never guess.
     *
     * Runs the self-check (no hand-written byte changed) AND a parse-guard (the candidate
     * parses and declares no duplicate class constant) before returning. Throws a
     * RuntimeException on any structural surprise, self-check failure, or parse-guard
     * failure; the caller skips the file.
     *
     * @param string $source          Full current file contents.
     * @param string $class_basename   e.g. "Contact_Model".
     * @param string $doc_block         The pre-class docblock text (no trailing newline).
     * @param string $constants_block   The post-brace enum-constants block, first line
     *                                   `    /**`, ending with a trailing newline.
     *                                   Empty string when the model has no enum constants.
     * @return string                   The rewritten file contents.
     */
    public static function rewrite(string $source, string $class_basename, string $doc_block, string $constants_block): string
    {
        $ast = static::__parse_or_throw($source, $class_basename);
        $class_node = static::__find_target_class($ast, $class_basename, $source);

        $region_a = static::__find_region_a($class_node, $source);
        $region_b1 = static::__find_enum_constants_region($class_node, $source);

        // Classify every B2 fence. A fence holding enum constants is the old-format home for the
        // enum-constants region and must be migrated; an empty fence is inert and left as-is;
        // an unclassifiable fence (non-constant content) fails loud.
        $consts_fences = [];
        foreach (static::__find_fence_pair_regions($ast, $source) as $fence) {
            $kind = static::__classify_fence_region($class_node, $source, $fence);
            if ($kind === 'unknown') {
                throw new RuntimeException(
                    "Structural surprise: a __AUTO_GENERATED fence in {$class_basename} holds content that is "
                    . "not enum constants; its ownership cannot be classified. Refusing to rewrite (skip the file)."
                );
            }
            if ($kind === 'consts') {
                $consts_fences[] = $fence;
            }
        }

        // Decide where the canonical enum-constants block is emitted, and which old-format
        // constant fences are dropped. Exactly one region receives the block; every other
        // constants-bearing region is removed so the file ends up with a single const set.
        $emit_region = null;   // [first_line, last_line] to replace with $constants_block
        $drop_ranges = [];     // [first_line, last_line] ranges removed with no replacement
        if ($region_b1 !== null) {
            $emit_region = $region_b1;
            $drop_ranges = $consts_fences;                       // old-format fences are redundant
        } elseif (!empty($consts_fences)) {
            $emit_region = $consts_fences[0];                    // migrate the first fence in place
            $drop_ranges = array_slice($consts_fences, 1);       // remove any further ones
        }

        $class_line = static::__offset_to_line($source, $class_node->getStartFilePos());
        $brace_offset = static::__find_class_brace_offset($source, $class_node);
        $brace_line = static::__offset_to_line($source, $brace_offset);

        $lines = explode("\n", $source);
        $doc_lines = explode("\n", $doc_block);
        $const_lines = $constants_block === '' ? [] : explode("\n", rtrim($constants_block, "\n"));

        $out = [];
        $i = 0;
        $n = count($lines);

        while ($i < $n) {
            // Region A: replace an existing auto docblock in place.
            if ($region_a !== null && $i === $region_a[0]) {
                foreach ($doc_lines as $dl) {
                    $out[] = $dl;
                }
                $i = $region_a[1] + 1;
                continue;
            }

            // Region A: no existing auto docblock - insert immediately before the class line.
            if ($region_a === null && $i === $class_line) {
                foreach ($doc_lines as $dl) {
                    $out[] = $dl;
                }
                // fall through to emit the class line itself
            }

            // Enum-constants region: replace it (B1 in place, or a migrated B2 fence) with
            // the canonical block. An empty $const_lines removes the region entirely (model
            // lost its enums), which correctly strips a stale fence's markers too.
            if ($emit_region !== null && $i === $emit_region[0]) {
                foreach ($const_lines as $cl) {
                    $out[] = $cl;
                }
                $i = $emit_region[1] + 1;
                continue;
            }

            // Drop a redundant old-format constants fence (owned content, no replacement here).
            $dropped = false;
            foreach ($drop_ranges as [$ds, $de]) {
                if ($i === $ds) {
                    $i = $de + 1;
                    $dropped = true;
                    break;
                }
            }
            if ($dropped) {
                continue;
            }

            // No existing enum-constants region anywhere - insert right after the brace line.
            if ($emit_region === null && $region_b1 === null && !empty($const_lines) && $i === $brace_line) {
                $out[] = $lines[$i];
                foreach ($const_lines as $cl) {
                    $out[] = $cl;
                }
                $i++;
                continue;
            }

            $out[] = $lines[$i];
            $i++;
        }

        $candidate = implode("\n", $out);

        // Requirement 3: mechanism-independent self-check. If any hand-written byte
        // changed, refuse the write.
        static::assert_no_handwritten_change($source, $candidate, $class_basename);

        // Hard safety net: the candidate must parse AND declare no duplicate class constant.
        // This catches the whole duplicate-const bug class mechanically, no matter how the
        // rewrite went wrong.
        static::__assert_candidate_is_sound($candidate, $class_basename);

        return $candidate;
    }

    /**
     * The self-check: strip all owned regions from both sides and require the remainder
     * (the hand-written content) to be byte-identical. Throws a RuntimeException naming
     * the class and the first differing line when they diverge.
     */
    public static function assert_no_handwritten_change(string $original, string $candidate, string $class_basename): void
    {
        $stripped_original = static::strip_owned_regions($original, $class_basename);
        $stripped_candidate = static::strip_owned_regions($candidate, $class_basename);

        if ($stripped_original === $stripped_candidate) {
            return;
        }

        $orig_lines = explode("\n", $stripped_original);
        $cand_lines = explode("\n", $stripped_candidate);
        $max = max(count($orig_lines), count($cand_lines));
        $first_diff = null;
        for ($i = 0; $i < $max; $i++) {
            $o = $orig_lines[$i] ?? '<missing>';
            $c = $cand_lines[$i] ?? '<missing>';
            if ($o !== $c) {
                $first_diff = "line " . ($i + 1) . ":\n      original: " . $o . "\n      candidate: " . $c;
                break;
            }
        }

        throw new RuntimeException(
            "Self-check FAILED for {$class_basename}: regeneration would alter hand-written "
            . "content outside the auto-generated fences. Refusing to write.\n    First difference at "
            . ($first_diff ?? 'unknown')
        );
    }

    /**
     * Remove every owned region (A, B1, B2) and return the remaining bytes. What is left
     * is exactly the hand-written content the codegen must never touch.
     */
    public static function strip_owned_regions(string $source, string $class_basename): string
    {
        $ast = static::__parse_or_throw($source, $class_basename);
        $class_node = static::__find_target_class($ast, $class_basename, $source);

        $ranges = [];

        $region_a = static::__find_region_a($class_node, $source);
        if ($region_a !== null) {
            $ranges[] = $region_a;
        }

        $region_b1 = static::__find_enum_constants_region($class_node, $source);
        if ($region_b1 !== null) {
            $ranges[] = $region_b1;
        }

        foreach (static::__find_fence_pair_regions($ast, $source) as $fence) {
            $ranges[] = $fence;
        }

        // Build the removal set of line indices.
        $remove = [];
        foreach ($ranges as [$start, $end]) {
            for ($l = $start; $l <= $end; $l++) {
                $remove[$l] = true;
            }
        }

        $lines = explode("\n", $source);
        $out = [];
        foreach ($lines as $index => $line) {
            if (isset($remove[$index])) {
                continue;
            }
            $out[] = $line;
        }

        return implode("\n", $out);
    }

    // -------------------------------------------------------------------------
    // Region detection (structural)
    // -------------------------------------------------------------------------

    /**
     * Region A: the pre-class docblock whose text contains `_AUTO_GENERATED_`. Returned
     * as [first_line, last_line] (0-based, inclusive), or null when absent. Throws when
     * more than one such docblock leads the class (a structural surprise).
     */
    protected static function __find_region_a(Node\Stmt\Class_ $class_node, string $source): ?array
    {
        $owned = [];
        foreach ($class_node->getComments() as $comment) {
            if (str_contains($comment->getText(), self::SINGLE_UNDERSCORE_MARKER)) {
                $owned[] = $comment;
            }
        }

        if (count($owned) === 0) {
            return null;
        }

        if (count($owned) > 1) {
            throw new RuntimeException(
                "Structural surprise: found " . count($owned)
                . " auto-generated docblocks before the class. Expected at most one."
            );
        }

        $comment = $owned[0];
        return [
            static::__offset_to_line($source, $comment->getStartFilePos()),
            static::__offset_to_line($source, $comment->getEndFilePos()),
        ];
    }

    /**
     * Region B1: the "_AUTO_GENERATED_ Enum constants" docblock plus the contiguous
     * run of const declarations it heads. Returned as [first_line, last_line]
     * (0-based, inclusive), or null when absent.
     *
     * The run terminates at the first non-const statement, the first const carrying its
     * own leading comment, or a blank line between consts (so a hand-written const set
     * off by a blank line is never swept into the owned region).
     */
    protected static function __find_enum_constants_region(Node\Stmt\Class_ $class_node, string $source): ?array
    {
        $stmts = $class_node->stmts;

        $head_index = null;
        $head_comment = null;
        foreach ($stmts as $index => $stmt) {
            if (!($stmt instanceof Node\Stmt\ClassConst)) {
                continue;
            }
            foreach ($stmt->getComments() as $comment) {
                if (str_contains($comment->getText(), self::ENUM_CONSTANTS_MARKER)) {
                    $head_index = $index;
                    $head_comment = $comment;
                    break 2;
                }
            }
        }

        if ($head_index === null) {
            return null;
        }

        $run_last = $stmts[$head_index];
        for ($j = $head_index + 1; $j < count($stmts); $j++) {
            $stmt = $stmts[$j];
            if (!($stmt instanceof Node\Stmt\ClassConst)) {
                break;
            }
            // A const carrying its own leading comment is not part of the plain generated run.
            if (count($stmt->getComments()) > 0) {
                break;
            }
            // A blank line between the previous run member and this one ends the run.
            $gap = substr($source, $run_last->getEndFilePos() + 1, $stmt->getStartFilePos() - $run_last->getEndFilePos() - 1);
            if (substr_count($gap, "\n") > 1) {
                break;
            }
            $run_last = $stmt;
        }

        return [
            static::__offset_to_line($source, $head_comment->getStartFilePos()),
            static::__offset_to_line($source, $run_last->getEndFilePos()),
        ];
    }

    /**
     * Region B2: every "__AUTO_GENERATED:" / "__/AUTO_GENERATED" fenced pair.
     * Returns a list of [first_line, last_line] (0-based, inclusive). Throws when markers
     * are unbalanced or out of order (a structural surprise).
     */
    protected static function __find_fence_pair_regions($ast, string $source): array
    {
        $comments = static::__collect_all_comments($ast);

        $markers = [];
        foreach ($comments as $comment) {
            $text = $comment->getText();
            if (str_contains($text, self::FENCE_OPEN_MARKER)) {
                $markers[] = ['type' => 'open', 'comment' => $comment];
            } elseif (str_contains($text, self::FENCE_CLOSE_MARKER)) {
                $markers[] = ['type' => 'close', 'comment' => $comment];
            }
        }

        usort($markers, fn($a, $b) => $a['comment']->getStartFilePos() <=> $b['comment']->getStartFilePos());

        $regions = [];
        $i = 0;
        while ($i < count($markers)) {
            if ($markers[$i]['type'] !== 'open') {
                throw new RuntimeException('Structural surprise: unbalanced __AUTO_GENERATED fence markers (close without open).');
            }
            if (!isset($markers[$i + 1]) || $markers[$i + 1]['type'] !== 'close') {
                throw new RuntimeException('Structural surprise: unbalanced __AUTO_GENERATED fence markers (open without close).');
            }
            $open = $markers[$i]['comment'];
            $close = $markers[$i + 1]['comment'];
            $regions[] = [
                static::__offset_to_line($source, $open->getStartFilePos()),
                static::__offset_to_line($source, $close->getEndFilePos()),
            ];
            $i += 2;
        }

        return $regions;
    }

    /**
     * Collect every comment attached anywhere in the AST (leading and trailing).
     */
    protected static function __collect_all_comments($ast): array
    {
        $collected = [];
        $visitor = new class($collected) extends NodeVisitorAbstract {
            public $out;
            public function __construct(&$out)
            {
                $this->out = &$out;
            }
            public function enterNode(Node $node)
            {
                foreach ($node->getComments() as $comment) {
                    // Key by start position to dedupe (a comment attaches to one node).
                    $this->out[$comment->getStartFilePos()] = $comment;
                }
                return null;
            }
        };
        $traverser = new NodeTraverser();
        $traverser->addVisitor($visitor);
        $traverser->traverse($ast);

        return array_values($collected);
    }

    /**
     * Classify the content of a single B2 fence region (its lines strictly between the
     * open and close markers). Returns:
     *   'consts'  - the fence holds one or more enum-constant declarations and nothing else
     *               (blank lines aside). This is the old-format enum-constants home; it may be
     *               migrated (removed) because everything inside a fence is owned.
     *   'empty'   - the fence holds only blank lines (constants already migrated out). Inert.
     *   'unknown' - the fence holds some non-blank line that is not a class-constant
     *               declaration (a hand-written comment, code, whatever). The caller must
     *               fail loud rather than guess at its ownership.
     *
     * Const membership is decided structurally: a content line counts as owned only if it
     * falls inside a ClassConst node the parser placed wholly within the fence.
     *
     * @param array $fence [first_line, last_line] (0-based, inclusive) of the fence pair.
     */
    protected static function __classify_fence_region(Node\Stmt\Class_ $class_node, string $source, array $fence): string
    {
        [$open_line, $close_line] = $fence;
        $lines = explode("\n", $source);

        // Line indices covered by a class-constant declaration sitting strictly inside the
        // fence (between the marker lines).
        $const_lines = [];
        foreach ($class_node->stmts as $stmt) {
            if (!($stmt instanceof Node\Stmt\ClassConst)) {
                continue;
            }
            $start = static::__offset_to_line($source, $stmt->getStartFilePos());
            $end = static::__offset_to_line($source, $stmt->getEndFilePos());
            if ($start > $open_line && $end < $close_line) {
                for ($l = $start; $l <= $end; $l++) {
                    $const_lines[$l] = true;
                }
            }
        }

        // Every non-blank line strictly between the markers must belong to one of those
        // consts; anything else is unclassifiable.
        for ($l = $open_line + 1; $l <= $close_line - 1; $l++) {
            if (trim($lines[$l] ?? '') === '') {
                continue;
            }
            if (!isset($const_lines[$l])) {
                return 'unknown';
            }
        }

        return count($const_lines) > 0 ? 'consts' : 'empty';
    }

    /**
     * Parse-guard: the rewritten candidate must be syntactically valid AND must not declare
     * the same class constant twice (the exact fatal - "Cannot redefine class constant" -
     * that a duplicate enum-constants block produces). php-parser catches syntax errors;
     * duplicate constant NAMES are syntactically legal, so they are checked explicitly on
     * the AST. Either failure throws, refusing the write.
     */
    protected static function __assert_candidate_is_sound(string $candidate, string $class_basename): void
    {
        $ast = static::__parse_or_throw($candidate, $class_basename);
        $class_node = static::__find_target_class($ast, $class_basename, $candidate);

        $seen = [];
        foreach ($class_node->stmts as $stmt) {
            if (!($stmt instanceof Node\Stmt\ClassConst)) {
                continue;
            }
            foreach ($stmt->consts as $const) {
                $name = $const->name->toString();
                if (isset($seen[$name])) {
                    throw new RuntimeException(
                        "Parse-guard FAILED for {$class_basename}: the rewrite would declare class constant "
                        . "'{$name}' more than once (a 'Cannot redefine class constant' fatal). Refusing to write."
                    );
                }
                $seen[$name] = true;
            }
        }
    }

    // -------------------------------------------------------------------------
    // Primitives
    // -------------------------------------------------------------------------

    protected static function __parse_or_throw(string $source, string $class_basename)
    {
        try {
            $ast = static::__parser()->parse($source);
        } catch (\PhpParser\Error $e) {
            throw new RuntimeException("Parse error while processing {$class_basename}: " . $e->getMessage());
        }

        if ($ast === null) {
            throw new RuntimeException("Parser returned no statements for {$class_basename}.");
        }

        return $ast;
    }

    /**
     * Find the single Class_ node whose short name matches $class_basename. Throws when
     * absent or ambiguous.
     */
    protected static function __find_target_class($ast, string $class_basename, string $source): Node\Stmt\Class_
    {
        $finder = new \PhpParser\NodeFinder();
        $matches = [];
        foreach ($finder->findInstanceOf($ast, Node\Stmt\Class_::class) as $class_node) {
            if ($class_node->name !== null && $class_node->name->toString() === $class_basename) {
                $matches[] = $class_node;
            }
        }

        if (count($matches) === 0) {
            throw new RuntimeException("Could not find class {$class_basename} in source.");
        }
        if (count($matches) > 1) {
            throw new RuntimeException("Found " . count($matches) . " classes named {$class_basename}; expected exactly one.");
        }

        return $matches[0];
    }

    /**
     * Byte offset of the class body opening brace. The class header (name, extends,
     * implements clauses) contains only identifiers, commas and whitespace, so the first
     * `{` at or after the class node start is the body brace.
     */
    protected static function __find_class_brace_offset(string $source, Node\Stmt\Class_ $class_node): int
    {
        $offset = strpos($source, '{', $class_node->getStartFilePos());
        if ($offset === false) {
            throw new RuntimeException('Structural surprise: could not locate the class opening brace.');
        }
        return $offset;
    }

    /**
     * 0-based line index of a byte offset (the number of newlines before it).
     */
    protected static function __offset_to_line(string $source, int $offset): int
    {
        if ($offset <= 0) {
            return 0;
        }
        return substr_count($source, "\n", 0, $offset);
    }
}
