<?php

namespace App\RSpade\Core\Csp;

use Illuminate\Http\Request;
use App\RSpade\Core\Controller\Rsx_Controller_Abstract;
use App\RSpade\Core\Time\Rsx_Time;

/**
 * Csp_Report_Controller - the violation collector named by every policy's report-uri.
 *
 * A browser posts here on its own, with no session cookie it controls, no CSRF token and a
 * vendor-specific content type (`application/csp-report`, or `application/reports+json` for
 * the newer Reporting API). It is a one-way drain: one JSON line per report appended to
 * storage/logs/csp_violations.log, and 204 in every case.
 *
 * IT NEVER ERRORS. A collector that 4xx'd a malformed body would teach browsers to retry and
 * turn a reporting channel into an error loop; a collector that threw would fill the
 * application log with noise generated by whatever a page happened to load. A body that is
 * not JSON is recorded verbatim (truncated) under an `invalid` key and still answers 204.
 *
 * NOT A CSRF SURFACE: the collector reads nothing and writes nothing but its own log, so it is
 * exempt at the Rsx_Csrf::enforce seam (which sees the path constant, not this class).
 *
 * NO TABLE IN v1. Triage is `tail`/`jq` over the log file; a report is diagnostic exhaust
 * during rollout, not application data.
 *
 * DEPLOYMENT NOTE: the path is served by the STAFF dispatcher. With the default prefix-based
 * portal detection a portal page posts here fine (/_csp-report is not under the portal
 * prefix). An install serving its portal from a SEPARATE DOMAIN would need the same path
 * routed there too; no such install exists today.
 *
 * See: php artisan rsx:man csp
 */
class Csp_Report_Controller extends Rsx_Controller_Abstract
{
    /** The log every report lands in. */
    public const LOG_FILENAME = 'csp_violations.log';

    /** How much of an unparseable body is worth keeping. */
    public const INVALID_BODY_KEPT_BYTES = 4096;

    /**
     * Accept one violation report (or a Reporting API batch) and record it.
     *
     * Gate is 'public' and must be: the reporter is a browser acting on its own behalf,
     * often on a page nobody is logged into. It carries no authority and reaches no data.
     *
     * @param Request $request
     * @param array $params
     * @return \Symfony\Component\HttpFoundation\Response
     */
    #[Route('/_csp-report', methods: ['POST'])]
    #[Auth('public')]
    public static function report(Request $request, array $params = [])
    {
        $body = $request->getContent();
        $decoded = json_decode($body, true);

        if (!is_array($decoded)) {
            static::__append([
                'invalid' => substr($body, 0, self::INVALID_BODY_KEPT_BYTES),
            ], $request);

            return response('', 204);
        }

        // Two wire shapes. `application/csp-report` sends one {"csp-report": {...}}; the
        // Reporting API sends a LIST of {type, url, body} envelopes.
        if (isset($decoded['csp-report'])) {
            static::__append(['report' => $decoded['csp-report']], $request);
        } elseif (array_is_list($decoded)) {
            foreach ($decoded as $entry) {
                static::__append(['report' => $entry], $request);
            }
        } else {
            static::__append(['report' => $decoded], $request);
        }

        return response('', 204);
    }

    /**
     * Append one JSON line. json_encode is what makes the line format safe: a report is
     * attacker-influenced text, and encoding it can never emit a raw newline.
     *
     * @param array $payload
     * @param Request $request
     * @return void
     */
    protected static function __append(array $payload, Request $request): void
    {
        $line = json_encode(array_merge([
            'at' => Rsx_Time::now_iso(),
            'user_agent' => (string) $request->header('User-Agent', ''),
        ], $payload), JSON_UNESCAPED_SLASHES);

        $directory = storage_path('logs');
        ensure_directory($directory);

        file_put_contents($directory . '/' . self::LOG_FILENAME, $line . "\n", FILE_APPEND);
    }
}
